config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  resources :todo_lists, except: :new do
    resources :comments, shallow: true, only: %i[index create destroy]
    resources :tasks, shallow: true, except: %i[index new show]
    resources :invites, shallow: true, only: %i[index create destroy] do
      member do
        get 'confirm'
      end
    end
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  belongs_to :todo_list

  validates :todo_list_id, :user_id, presence: true
  validates :user_id, uniqueness: {scope: :todo_list_id, message: 'this user already have invite for this todo list'}
  validate :it_is_todo_list_owner, if: :todo_list_id

  has_secure_token :invite_token, length: 36

  after_create :send_invite_email

  private

  def it_is_todo_list_owner
    errors.add(:user, 'This user is todo list owner') if user&.todo_lists&.exists? id: todo_list.id
  end

  def send_invite_email
    InviteMailer.with(invite: self).invite_email.deliver_now
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!

  def index
    @todo_list = current_user.todo_lists.find_by(id: params[:todo_list_id])
    if @todo_list.nil?
      flash[:alert] = 'Todo list is not found'
      redirect_back(fallback_location: todo_lists_path)
    end
  end

  def create
    user = User.find_by_email(invite_params[:email])
    if user.nil?
      flash[:alert] = 'User not found in system'
      return redirect_to todo_list_path params[:todo_list_id]
    end
    todo_list = current_user.todo_lists.find(params[:todo_list_id])
    @invite = Invite.create(user: user, todo_list: todo_list)
    if @invite.invalid?
      flash[:alert] = @invite.errors.full_messages.join(' | ')
    else
      flash[:notice] = 'invite has been send to email'
    end
    redirect_to todo_list
  end

  def confirm
    invite = Invite.find_by_invite_token(params[:id])
    invite.update(confirm: true) if current_user == invite.user
    flash[:notice] = 'Now you have access to this todo list'
    redirect_to invite.todo_list
  end

  def destroy
    invite = Invite.find(params[:id])
    unless invite.todo_list.user == current_user
      flash[:alert] = 'You have not access to manage this invite'
      return redirect_to todo_lists_path
    end

    invite.destroy
    flash['notice'] = 'Invite has been successful canceled!'
    redirect_to todo_list_invites_path invite.todo_list
  end

  private

  def invite_params
    params.require(:invite).permit(:email)
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/index.html.erb
<!--<h2>Members for '<%#= @todo_list.title %>' todo list:</h2>-->

<%# if @todo_list.members.empty? %>
<!--  <h4>Member list is empty</h4>-->
<%# else %>
<!--  <ul>-->
<%# @todo_list.invites.each do |invite| %>
<!--      <li><%#= invite.user.name %> | <%#= invite.user.email %> | <%#= invite.confirm %>-->
<!--        | <%#= link_to 'cancel', invite_path(invite), method: :delete %></li>-->
<%# end %>
<!--  </ul>-->
<%# end %>


<main id="todo-list-bg" class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card table-responsive-md bg-light p-3">
          <div class="row justify-content-end">
            <div>
              <%= link_to 'Back', todo_list_path(@todo_list), class: %w[btn btn-sm btn-rounded btn-primary my-3] %>
            </div>
          </div>
          <h4 class="h4">Members for '<span class="text-black-50"><%= @todo_list.title %></span>' todo list</h4>
          <% if @todo_list.members.empty? %>
            <h5 class="small">Member list is empty</h5>
          <% else %>
            <table class="table caption-top table-hover">
              <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
              </tr>
              </thead>
              <tbody>
              <% @todo_list.invites.each_with_index do |invite, index| %>
                <tr>
                  <th scope="row"><%= index + 1 %></th>
                  <td><%= invite.user.name %></td>
                  <td><%= invite.user.email %></td>
                  <td><%= invite.confirm %></td>
                  <td><%= link_to 'cancel', invite_path(invite), method: :delete, class: %w[btn btn-sm btn-link] %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>