config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  resources :todo_lists, except: :new do
    resources :comments, shallow: true, only: %i[index create destroy]
    resources :tasks, shallow: true, except: %i[index new show]
    resources :invites, shallow: true, only: %i[index create destroy] do
      member do
        get 'confirm'
      end
    end
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :tasks, dependent: :delete_all
  has_many :invites, dependent: :delete_all
  has_many :members, through: :invites, source: :user
  has_many :comments, dependent: :delete_all
  belongs_to :user

  validates :title, presence: true
end

app/controllers/todo_lists_controller.rb
# frozen_string_literal: true
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_have_access?, only: :show

  def index
    @todo_lists = current_user.todo_lists
    @confirmed_invites = current_user.invites.where(confirm: true)
  end

  def show; end

  def create
    todo_list = TodoList.create(todo_list_params_with_user)
    if todo_list.invalid?
      flash[:alert] = todo_list.errors.full_messages.join(' | ')
    else
      flash[:notice] = 'Todo list has been successful created!'
    end
    redirect_to todo_lists_path
  end

  def edit
    @todo_list = current_user.todo_lists.find_by(id: params[:id])
    if @todo_list.nil?
      flash[:alert] = 'Todo list is not found'
      redirect_to todo_lists_path
    end
  end

  def update
    @todo_list = current_user.todo_lists.find_by(id: params[:id])
    if @todo_list.nil?
      flash[:alert] = 'Todo list is not found'
      return redirect_to todo_lists_path
    end
    @todo_list.update(todo_list_params)
    if @todo_list.invalid?
      flash.now[:alert] = @todo_list.errors.full_messages.join(' | ')
      return render :edit
    end
    flash[:notice] = 'Todo list has been successful updated!'
    redirect_to todo_lists_path
  end

  def destroy
    @todo_list = current_user.todo_lists.find_by(id: params[:id])
    if @todo_list.nil?
      flash[:alert] = 'Todo List is not found'
      return redirect_to todo_lists_path
    end
    @todo_list.destroy
    flash[:notice] = 'Todo list has been successful destroyed!'
    redirect_to todo_lists_path
  end


  private

  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end

  def todo_list_params_with_user
    todo_list_params.merge(user: current_user)
  end

  def user_have_access?
    @todo_list = TodoList.find(params[:id])
    unless @todo_list.user == current_user ||
        (@todo_list.members.exists?(current_user.id) && @todo_list.invites.find_by_user_id(current_user.id).confirm)
      flash[:alert] = 'You have not access to this todo list'
      redirect_to todo_lists_path
    end
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/edit.html.erb
<!--<h2>Edit '<%#= @todo_list.title %>' todo list</h2>-->

<%#= form_with model: @todo_list, url: todo_list_path, method: :put do |form| %>
<!--  <div class="field_with_errors">-->
<%#= form.label :title %>
<%#= form.text_field :title %>
<!--  </div>-->
<!--  <div class="field_with_errors">-->
<%#= form.label :description %>
<%#= form.text_area :description %>
<!--  </div>-->
<%#= form.submit %>
<%# end %>

<%#= link_to 'delete', todo_list_path(@todo_list), method: :delete %>


<main id="todo-list-bg" class="py-5">
  <div class="mask d-flex align-items-center h-100">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-xl-5 col-md-8">
          <%= form_with model: @todo_list, url: todo_list_path, html: {class: %w[bg-white rounded shadow-5-strong p-5]}, method: :put do |form| %>

            <h3 class="text-black-50 text-center mb-4">Edit</h3>

            <div class="mb-4">
              <%= form.label :title, class: 'form-label' %>
              <%= form.text_field :title, class: 'form-control' %>
            </div>
            <div class="mb-4">
              <%= form.label :description, class: 'form-label' %>
              <%= form.text_area :description, class: 'form-control' %>
            </div>
            <%= form.submit 'update', class: %w[btn btn-primary btn-sm btn-block] %>
            <%= link_to 'delete', todo_list_path(@todo_list), data: {confirm: 'are you sure want delete this todo?'}, method: :delete, class: %w[btn btn-danger btn-sm btn-block] %>

            <%= link_to "back", todo_lists_path, class: %w[btn btn-link btn-sm mt-5 btn-block] %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/todo_lists/index.html.erb
<!--<h2>It`s my todo lists:</h2>-->

<%# if @todo_lists.empty? %>
<!--  <h3>Todo lists - empty</h3>-->
<%# else %>
<!--  <ul>-->
<%# @todo_lists.each do |todo| %>
<!--      <li><%#= link_to todo.title, todo_list_path(todo) %> | <%#= link_to 'Edit', edit_todo_list_path(todo) %></li>-->
<%# end %>
<!--  </ul>-->
<%# end %>


<!--<h4>Create new todo list: </h4>-->

<%#= form_with scope: :todo_list, url: todo_lists_path, method: :post do |form| %>
<!--  <div class="field_with_errors">-->
<%#= form.label :title %>
<%#= form.text_field :title %>
<!--  </div>-->
<!--  <div class="field_with_errors">-->
<%#= form.label :description %>
<%#= form.text_area :description %>
<!--  </div>-->
<%#= form.submit %>
<%# end %>


<!--<h4>Available to you todo lists: </h4>-->

<%# if @confirmed_invites.empty? %>
<!--  <h4>Have not available todo lists</h4>-->
<%# else %>
<!--  <ul>-->
<%# @confirmed_invites.each do |invite| %>
<!--      <li><%#= link_to invite.todo_list.title, todo_list_path(invite.todo_list) %></li>-->
<%# end %>
<!--  </ul>-->
<%# end %>


<main id="todo-list-bg" class="pb-5">
  <div class="container">
    <section class="text-center text-md-start">
      <h4 class="mb-4 pt-5"><strong>It`s my todo lists</strong></h4>
      <% if @todo_lists.empty? %>
        <h3>Todo lists - empty</h3>
      <% else %>
        <div class="row align-items-stretch">
          <% @todo_lists.each do |todo| %>
            <div class="col-lg-4 col-md-12 mb-4">
              <div class="card shadow-5-strong bg-light" style="height: 100%">
                <div class="card-body">
                  <h5 class="card-title"><%= link_to todo.title, todo_list_path(todo) %></h5>
                  <p class="small"><%= todo.created_at.strftime("%F %T") %></p>
                  <p class="card-text">
                    <%= todo.description %>
                  </p>
                  <%= link_to 'open', todo_list_path(todo), class: %w[btn btn-sm btn-rounded btn-primary] %>
                  <%= link_to 'Edit', edit_todo_list_path(todo), class: %w[btn btn-sm btn-rounded btn-link] %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </section>

    <h4 class="pt-5 mb-4 text-md-start text-center"><strong>Create new todo list</strong></h4>

    <%= form_with scope: :todo_list, url: todo_lists_path, html: {class: %w[bg-light rounded shadow-5-strong p-5]}, method: :post do |form| %>
      <div class="mb-4">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label :description, class: 'form-label' %>
        <%= form.text_area :description, rows: 5, class: 'form-control' %>
      </div>
      <%= form.submit 'add todo list', class: %w[btn btn-sm btn-primary] %>
    <% end %>

    <h4 class="pt-5 mb-4 text-md-start text-center"><strong>Available to you todo lists</strong></h4>

    <% if @confirmed_invites.empty? %>
      <h5><strong>Have not available todo lists</strong></h5>
    <% else %>
      <div class="row align-items-stretch">
        <% @confirmed_invites.each do |invite| %>
          <div class="col-lg-4 col-md-12 mb-4">
            <div class="card shadow-5-strong bg-light" style="height: 100%">
              <div class="card-body">
                <h5 class="card-title"><%= link_to invite.todo_list.title, todo_list_path(invite.todo_list) %></h5>
                <p class="small">owner: <%= invite.todo_list.user.name %>
                  | <%= invite.todo_list.created_at.strftime("%F %T") %></p>
                <p class="card-text">
                  <%= invite.todo_list.description %>
                </p>
                <%= link_to 'open', todo_list_path(invite.todo_list), class: %w[btn btn-sm btn-rounded btn-primary] %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</main>

app/views/todo_lists/show.html.erb
<!--<h2><%#= @todo_list.title %></h2>-->

<%# if @todo_list.tasks.empty? %>
<!--  <h4>Todo list have not tasks</h4>-->
<%# else %>
<!--  <ul>-->
<%# @todo_list.tasks.each do |task| %>
<!--      <li><%#= task.title %> | <%#= task.priority.name %> | <%#= task.deadline %>-->
<!--        <%# if @todo_list.user == current_user %> | <%#= link_to 'Edit', edit_task_path(task) %>-->
<!--        <%# end %></li>-->
<%# end %>
<!--  </ul>-->
<%# end %>

<%# if @todo_list.user == current_user %>
<!--  <h4>Add task to todo list:</h4>-->

<%#= form_with scope: :task, url: todo_list_tasks_path(@todo_list), method: :post do |form| %>
<!--    <div class="field_with_errors">-->
<%#= form.label :title %>
<%#= form.text_field :title %>
<!--    </div>-->
<!--    <div class="field_with_errors">-->
<%#= form.label :description %>
<%#= form.text_area :description %>
<!--    </div>-->
<!--    <div class="field_with_errors">-->
<%#= form.label :deadline %>
<%#= form.datetime_local_field :deadline %>
<!--    </div>-->
<!--    <div class="field_with_errors">-->
<%#= form.label :priority %>
<%#= form.collection_select :priority_id, Priority.order(:level), :id, :name %>
<!--    </div>-->
<%#= form.submit %>
<%# end %>


<!--  <h4>You can invite other people to your todo list: </h4>-->

<%#= form_with scope: :invite, url: todo_list_invites_path(@todo_list), method: :post do |form| %>
<!--    <div class="field">-->
<%#= form.label :email %>
<%#= form.email_field :email %>
<!--    </div>-->
<%#= form.submit 'Send invite' %>
<%# end %>

<%#= link_to 'show all members', todo_list_invites_path(@todo_list) %>

<%# end %>


<!--<h4>Comments</h4>-->

<%# if @todo_list.comments.empty? %>
<!--  <h5>Todo list have not comments</h5>-->
<%# else %>
<!--  <ul>-->
<%# @todo_list.comments.limit(10).order(created_at: :desc).each do |comment| %>
<!--      <li>-->
<!--        <h5><%#= comment.user.name %> | <%#= comment.created_at %></h5>-->
<!--        <p><%#= comment.text %></p>-->
<%# if @todo_list.user == current_user %>
<%#= link_to 'delete', comment_path(comment), method: :delete %>
<%# end %>
<!--      </li>-->
<!--      <hr>-->
<%# end %>
<!--  </ul>-->
<%# end %>

<%# if @todo_list.comments.size > 5 %>
<%#= link_to 'show all comments', todo_list_comments_path(@todo_list) %>
<%# end %>


<%#= form_with scope: :comment, url: todo_list_comments_path(@todo_list), method: :post do |form| %>
<!--  <div class="field">-->
<%#= form.label :text %>
<%#= form.text_area :text %>
<!--  </div>-->
<%#= form.submit 'send comment' %>
<%# end %>


<main id="todo-list-bg" class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card table-responsive-md bg-light p-3">
          <div class="row justify-content-end">
            <div>
              <%= link_to 'All todo lists', todo_lists_path, class: %w[btn btn-sm btn-rounded btn-primary my-3] %>
            </div>
          </div>
          <% if @todo_list.tasks.empty? %>
            <h3 class="h3 text-capitalize text-center">Todo list have not tasks</h3>
          <% else %>
            <table class="table caption-top table-hover">
              <thead>
              <caption class="h3 text-capitalize">
                <%= @todo_list.title %>
              </caption>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Priority</th>
                <th scope="col">Deadline</th>
                <th scope="col"></th>
              </tr>
              </thead>
              <tbody>
              <% @todo_list.tasks.each_with_index do |task, index| %>
                <tr>
                  <th scope="row"><%= index + 1 %></th>
                  <td><%= task.title %></td>
                  <td><%= task.description %></td>
                  <td><%= task.priority.name %></td>
                  <td><%= task.deadline.strftime("%F %T") %></td>
                  <td>
                    <% if @todo_list.user == current_user %>
                      <%= link_to 'Edit', edit_task_path(task), class: %w[btn btn-sm btn-link] %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>

    <% if @todo_list.user == current_user %>

      <div class="row mt-3 justify-content-center">
        <div class="col-md-8">
          <div class="card bg-light p-4">
            <h3 class="h3 text-center">Add task to todo list</h3>
            <%= form_with scope: :task, url: todo_list_tasks_path(@todo_list), method: :post do |form| %>
              <div class="mb-4">
                <%= form.label :title, class: 'form-label' %>
                <%= form.text_field :title, class: 'form-control' %>
              </div>
              <div class="mb-4">
                <%= form.label :description, class: 'form-label' %>
                <%= form.text_area :description, class: 'form-control', rows: 5 %>
              </div>
              <div class="mb-4">
                <%= form.label :deadline, class: 'form-label' %>
                <%= form.datetime_local_field :deadline, class: 'form-control' %>
              </div>
              <div class="mb-4">
                <%= form.label :priority, class: 'form-label' %>
                <%= form.collection_select :priority_id, Priority.order(:level), :id, :name, {prompt: false}, {class: "form-select"} %>
              </div>
              <%= form.submit 'add task', class: %w[btn btn-sm btn-primary] %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row mt-3 justify-content-center">
        <div class="col-md-8">
          <div class="card bg-light p-4">
            <h3 class="h3 mb-3 text-center">You can invite other people to your todo list</h3>
            <%= form_with scope: :invite, url: todo_list_invites_path(@todo_list), method: :post do |form| %>
              <div class="mb-4">
                <%= form.label :email, class: 'form-label' %>
                <%= form.email_field :email, class: 'form-control' %>
              </div>
              <%= form.submit 'Send invite', class: %w[btn btn-sm btn-primary mb-4] %>
            <% end %>

            <%= link_to 'show all members', todo_list_invites_path(@todo_list), class: %w[btn btn-sm btn-link] %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row mt-3 justify-content-center">
      <div class="col-md-8">
        <div class="card bg-light p-4">
          <h3 class="h3 mb-3 text-center">Comments</h3>
          <% if @todo_list.comments.empty? %>
            <h5>Todo list have not comments</h5>
          <% else %>
            <ul class="list-unstyled">
              <% @todo_list.comments.limit(3).order(created_at: :desc).each do |comment| %>
                <li class="bg-white card p-4">
                  <div class="comment-header d-md-flex justify-content-between">
                    <h5 class="small"><%= comment.user.name %></h5>
                    <h5 class="small"><%= comment.created_at.strftime('%F %T') %></h5>
                  </div>
                  <p><%= comment.text %></p>
                  <% if @todo_list.user == current_user %>
                    <div class="delete-btn d-flex justify-content-end">
                      <%= link_to 'X', comment_path(comment), method: :delete, data: {confirm: 'are you sure want delete this comment?'}, class: %w[btn btn-rounded btn-sm btn-danger] %>
                    </div>
                  <% end %>
                </li>
                <hr>
              <% end %>
            </ul>
          <% end %>

          <% if @todo_list.comments.size > 3 %>
            <%= link_to 'show all comments', todo_list_comments_path(@todo_list), class: %w[btn btn-sm btn-link mb-5] %>
          <% end %>


          <%= form_with scope: :comment, url: todo_list_comments_path(@todo_list), method: :post do |form| %>
            <div class="mb-4">
              <%= form.label :comment, class: 'form-label' %>
              <%= form.text_area :text, class: 'form-control', rows: 5 %>
            </div>
            <%= form.submit 'send comment', class: %w[btn btn-sm btn-primary] %>
          <% end %>

        </div>
      </div>
    </div>


  </div>
</main>