config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  resources :todo_lists, except: :new do
    resources :comments, shallow: true, only: %i[index create destroy]
    resources :tasks, shallow: true, except: %i[index new show]
    resources :invites, shallow: true, only: %i[index create destroy] do
      member do
        get 'confirm'
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!--<h1>Simple todo application</h1>-->

<%# if user_signed_in? %>
<!--  <h3>Hi <%#= current_user.name %>!</h3>-->
<!--  <%#= link_to 'My todo lists', todo_lists_path, method: :get %> <br>-->
<!--  <hr>-->
<%#= link_to 'Log out', destroy_user_session_path, method: :delete %>
<%# else %>
<!--  <%#= link_to 'Sign in', new_user_session_path %> |-->
<%#= link_to 'Sign up', new_user_registration_path %>
<%# end %>


<div id="intro" class="bg-image shadow-2-strong">
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.8);">
    <div class="container d-flex align-items-center justify-content-center text-center h-100">
      <div class="text-white">
        <h1 class="mb-3">Simple todo application</h1>
        <% if user_signed_in? %>
          <h3>Hi <%= current_user.name %>!</h3>
          <%= link_to 'My todo lists', todo_lists_path, method: :get, class: %w[btn btn-outline-light btn-lg m-2] %>
          <br>
          <hr>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: %w[btn btn-sm btn-outline-light btn-lg m-2] %>
        <% else %>
          <h5 class="mb-4">For using this app you need sign in or sign up</h5>
          <%= link_to 'Sign in', new_user_session_path, class: %w[btn btn-outline-light btn-lg m-2] %>
          <%= link_to 'Sign up', new_user_registration_path, class: %w[btn btn-outline-light btn-lg m-2] %>
        <% end %>
      </div>
    </div>
  </div>
</div>